CREATE TABLE TRUCK (
    SERIAL_NUMBER   VARCHAR(100) NOT NULL,
    WEIGHT_LIMIT_KG FLOAT,
    BATTERY_CAPACITY_PRCNT INTEGER,
    STATE VARCHAR,
    PRIMARY KEY (SERIAL_NUMBER)
);

CREATE TABLE BOX (
    ID INTEGER NOT NULL,
    WEIGHT FLOAT,
    CODE VARCHAR,
    IMAGE_URL VARCHAR,
    TRUCK_ID VARCHAR,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;